version: '3.1'

services:

  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpw
      MYSQL_DATABASE: ragdb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - rag-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpw
  
  chromadb:
    image: chromadb/chroma
    ports:
      - "8000:8000"
    networks:
      - rag-network
      
  backend:
    build:
      context: ./rag-poc
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - db
      - chromadb
    networks:
      - rag-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - rag-network

volumes:
  db_data:

networks:
  rag-network: